# Generated by Django 5.1 on 2024-09-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_order_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=True),
        ),
    ]
